#!/usr/bin/env python
import optparse,subprocess,os,sys,tempfile

# Set default values
statpath_name = "SVERIF_STATPATH"

# Retrieve CL arguments
usage = "%prog [options] FILE(S)"
parser = optparse.OptionParser(usage=usage)
parser.add_option("-n","--name",dest="var",default="GZ",
                  help="atmospheric variable name [default GZ]",metavar="VARIABLE")
parser.add_option("-l","--level",dest="level",default=500,
                  help="pressure level (mb) [default 500]",metavar="PRESSURE")
parser.add_option("-p","--prog",dest="prog",default=120,
                  help="forecast (prog) hour ][default 120]",metavar="HOUR")
parser.add_option("-c","--ci",dest="ci",default='0.05,0.01',
                  help="confindence intervals [default '0.05,0.01']",metavar="INTERVALS")
parser.add_option("-s","--statpath",dest="statpath",default=os.getenv(statpath_name),
                  help="path to statistics produced by prep [default "+statpath_name+"="+str(os.getenv(statpath_name))+"]",
                  metavar="PATH")
parser.add_option("-b","--boot",dest="nboot",default=1000,
                  help="number of samples for bootstrapping [default 1000]",metavar="NUMBER")
parser.add_option("-i","--inflation",dest="inflation",default=0,
                  help="scaling of parametric inflation for small samples [default 0]",metavar="NUMBER")
parser.add_option("-t","--threads",dest="threads",default=1,
                  help="number of OpenMP threads to run [default 1]",metavar="NUMBER")
parser.add_option("-v","--verbose",dest="verbose",default=False,action="store_true",
                  help="emit verbose output",metavar="NAME")
(options,args) = parser.parse_args()

# Check for at least one data file
if len(args) < 1:
    parser.print_usage()
    sys.exit(1)

# Check that stat file and data files exist
if not options.statpath:
    sys.stderr.write("Statistics path must be defined with --statpath if ${"+statpath_name+"} is not set\n")
    sys.exit(1)
if not os.path.isdir(options.statpath):
    try:
        os.makedirs(options.statpath)
    except OSError:
        sys.stderr.write("Cannot create "+statpath+"\n")
        sys.exit(1)
for path in args:
    if not os.path.isfile(path):
        sys.stderr.write("File "+path+" does not exist\n")
        sys.exit(1)

# Split requested confidence intervals
cisplit = options.ci.split(',')
cinum = len(cisplit)
ci = ' '.join(cisplit)

# Temporary file for R-Ftn exchange
fd = tempfile.NamedTemporaryFile()

# Call R script for processing
script_path = os.path.dirname(os.path.abspath(sys.argv[0]))
command = 'export OMP_NUM_THREADS='+str(options.threads)+'; R'+' --no-save --no-restore --args '+options.var+' '+ \
          str(options.level)+' '+str(options.prog)+' '+fd.name+' '+options.statpath+' '+str(options.nboot)+' '+ \
          str(options.inflation)+' '+str(cinum)+' '+ci+' '+ ' '.join(args)+' <'+os.path.join(script_path,'prep.R')
if (options.verbose): sys.stdout.write(command+'\n')
p = subprocess.Popen(command,shell=True,stdout=subprocess.PIPE,stderr=subprocess.PIPE)
error_message = p.stderr.read().rstrip('\n')
output_message = p.stdout.read().rstrip('\n')
if (options.verbose): sys.stdout.write(output_message+'\n')
if (error_message):
    sys.stderr.write(error_message+'\n')
    sys.exit(1)
sys.exit(0)
